In [1]:
import json
import time
from web3scout import *

In [2]:
PAIR_ADDRESS_UNIV3 = "0x8ad599c3a0ff1de082011efddc58f1908eb6e6d8"
PROVIDER_URL = "https://mainnet.infura.io/v3/xxxxxxxxxxxxxxxxx"
PLATFORM = Platform.AGNOSTIC
ABI_NAME_UNIV3 = JSONContract.UniswapV3Pool

In [3]:
abi = ABILoad(PLATFORM, ABI_NAME_UNIV3)
connect = ConnectW3(PROVIDER_URL)
connect.apply()

### (1) Extract Mint Events

In [4]:
rEvents = RetrieveEvents(connect, abi)
last_block = rEvents.latest_block()
start_block = last_block - 2000

In [5]:
events = rEvents.apply(EventType.MINT, address = PAIR_ADDRESS_UNIV3, start_block=start_block, end_block=last_block)
rEvents.to_dataframe(events).head(2)

,blockNumber,event,address,blockHash,logIndex,transactionHash,transactionIndex,args
0,23463948,Mint,0x8ad599c3A0ff1De082011EFDDc58f1908eb6e6D8,0xec927676fe28a0726104aa70cf3bd59b76ba66af40f1...,505,0x4cee13dee6e51e8004755939261797d6017bee978af9...,195,{'owner': '0xC36442b4a4522E871399CD717aBDD847A...
1,23464797,Mint,0x8ad599c3A0ff1De082011EFDDc58f1908eb6e6D8,0x7cc3e7aa51b6dfa77822a263c6a4d4b7b95701e811a0...,92,0x98a4930de3206c2542eea8a3f50cee357b460cf90c07...,15,{'owner': '0xC36442b4a4522E871399CD717aBDD847A...

### (2) Extract Swap Events

In [7]:
time.sleep(2)

In [9]:
rEvents = RetrieveEvents(connect, abi)
last_block = rEvents.latest_block()
start_block = last_block - 100

In [6]:
events = rEvents.apply(EventType.SWAP, address = PAIR_ADDRESS_UNIV3, start_block=start_block, end_block=last_block)
rEvents.to_dataframe(events).head(2)

,blockNumber,event,address,blockHash,logIndex,transactionHash,transactionIndex,args
0,23463249,Swap,0x8ad599c3A0ff1De082011EFDDc58f1908eb6e6D8,0xd99684ee0ba784e97bbf73019051c747bf22686609f5...,353,0xfe87c333f953610d01f268451d693480fd74b620c55a...,116,{'sender': '0x06CFf7088619C7178F5e14f0B119458d...
1,23463259,Swap,0x8ad599c3A0ff1De082011EFDDc58f1908eb6e6D8,0x910ba3c3c849c7a47319a8f82de2000a9910bd04cc2e...,372,0x81f0e551eeacb07f01b01026e5d732b4ecd33d7e3baf...,82,{'sender': '0x6745024462ABf2C049F54B381C4ad4a8...

### (3) Extract Burn Events

In [13]:
time.sleep(2)

In [10]:
rEvents = RetrieveEvents(connect, abi)
last_block = rEvents.latest_block()
start_block = last_block - 2000

In [11]:
events = rEvents.apply(EventType.BURN, address = PAIR_ADDRESS_UNIV3, start_block=start_block, end_block=last_block)
rEvents.to_dataframe(events).head(2)

,blockNumber,event,address,blockHash,logIndex,transactionHash,transactionIndex,args
0,23463279,Burn,0x8ad599c3A0ff1De082011EFDDc58f1908eb6e6D8,0xec217ce5bded3d2f3c324aa04c4cbaf54fae97007e00...,564,0x13c64c93dba434a78311fbe302884254a9970f22de5b...,179,{'owner': '0xC36442b4a4522E871399CD717aBDD847A...
1,23463701,Burn,0x8ad599c3A0ff1De082011EFDDc58f1908eb6e6D8,0xf9d7ec3a781100b142aafa79c1c7a29b66b64f609f1d...,559,0x792c100caffc6e33a2a2c06fbea316308ede2153e91e...,225,{'owner': '0xC36442b4a4522E871399CD717aBDD847A...