In [12]:
import json
import time
from web3scout import *

In [22]:
PAIR_ADDRESS_UNIV2 = "0xB4e16d0168e52d35CaCD2c6185b44281Ec28C9Dc"
PROVIDER_URL = "https://mainnet.infura.io/v3/xxxxxxxxxxx"
PLATFORM = Platform.AGNOSTIC
ABI_NAME_UNIV2 = JSONContract.UniswapV2Pair

In [15]:
abi = ABILoad(PLATFORM, ABI_NAME_UNIV2)
connect = ConnectW3(PROVIDER_URL)
connect.apply()

### (1) Extract Mint Events

In [16]:
time.sleep(2)

In [20]:
rEvents = RetrieveEvents(connect, abi)
last_block = rEvents.latest_block()
start_block = last_block - 30000

In [21]:
events = rEvents.apply(EventType.MINT, address = PAIR_ADDRESS_UNIV2, start_block=start_block, end_block=last_block)
rEvents.to_dataframe(events).head(2)

,blockNumber,event,address,blockHash,logIndex,transactionHash,transactionIndex,args
0,23436911,Mint,0xB4e16d0168e52d35CaCD2c6185b44281Ec28C9Dc,0xecaf048dc83065f8ad38a740c1017e3746dc75c54774...,373,0x91569868b43d2da289ba935f1e41e8e2cfbfea28cac9...,103,{'sender': '0x7a250d5630B4cF539739dF2C5dAcb4c6...
1,23437495,Mint,0xB4e16d0168e52d35CaCD2c6185b44281Ec28C9Dc,0x48ccca149d7f6bfde183b90733d623a7c2d7aa31c992...,351,0x3aeaab5c3b37e7dcf5222f4f1548df6f1559c7f1670e...,65,{'sender': '0x7a250d5630B4cF539739dF2C5dAcb4c6...

### (2) Extract Swap Events

In [24]:
time.sleep(2)

In [23]:
rEvents = RetrieveEvents(connect, abi)
last_block = rEvents.latest_block()
start_block = last_block - 30000

In [24]:
events = rEvents.apply(EventType.SWAP, address = PAIR_ADDRESS_UNIV2, start_block=start_block, end_block=last_block)
rEvents.to_dataframe(events).head(2)

,blockNumber,event,address,blockHash,logIndex,transactionHash,transactionIndex,args
0,23435463,Swap,0xB4e16d0168e52d35CaCD2c6185b44281Ec28C9Dc,0x60656d6c95fa412074acaa2e39143dddb934e909a034...,290,0x46f34ca72112eee89c2524493c83b2055d2f64272b23...,66,{'sender': '0x66a9893cC07D91D95644AEDD05D03f95...
1,23435465,Swap,0xB4e16d0168e52d35CaCD2c6185b44281Ec28C9Dc,0x4cb9d1486781ded92c59ef347b7817d5f9f98082865f...,758,0x2dcdecaef31f534c163a155b5505e8729d46e92db5fc...,296,{'sender': '0x1111111254EEB25477B68fb85Ed929f7...

### (3) Extract Burn Events

In [25]:
time.sleep(2)

In [30]:
rEvents = RetrieveEvents(connect, abi)
last_block = rEvents.latest_block()
start_block = last_block - 25000

In [31]:
events = rEvents.apply(EventType.BURN, address = PAIR_ADDRESS_UNIV2, start_block=start_block, end_block=last_block)
rEvents.to_dataframe(events).head(2)

,blockNumber,event,address,blockHash,logIndex,transactionHash,transactionIndex,args
0,23442297,Burn,0xB4e16d0168e52d35CaCD2c6185b44281Ec28C9Dc,0x7175112204acece784be97732ab1b95b46e9f8d44cf6...,994,0x8881c539057c4031f7e53549b8ea1ecb915eb2b2cbf0...,321,{'sender': '0x7a250d5630B4cF539739dF2C5dAcb4c6...
1,23443843,Burn,0xB4e16d0168e52d35CaCD2c6185b44281Ec28C9Dc,0xbeb9026446bd75b330d4001f238f9fe30b0a35b416b0...,403,0x32cfdfd2ca78dc5f21a7f19d0d15888c44110c3fe6d2...,60,{'sender': '0x0e00E9F2Ed00003b37dc611D41b10029...

### (4) Extract Sync Events (Price Oracle)

In [32]:
time.sleep(2)

In [33]:
rEvents = RetrieveEvents(connect, abi)
last_block = rEvents.latest_block()
start_block = last_block - 25000

In [34]:
events = rEvents.apply(EventType.SYNC, address = PAIR_ADDRESS_UNIV2, start_block=start_block, end_block=last_block)
rEvents.to_dataframe(events).head(2)

,blockNumber,event,address,blockHash,logIndex,transactionHash,transactionIndex,args
0,23440464,Sync,0xB4e16d0168e52d35CaCD2c6185b44281Ec28C9Dc,0x66e46ab760374b08ddccab815720818dc9cd9883630b...,264,0x2655baab01d2b51e0d1adc7d5ac56b11e203ca59dbdd...,54,"{'reserve0': 13869767063764, 'reserve1': 35007..."
1,23440464,Sync,0xB4e16d0168e52d35CaCD2c6185b44281Ec28C9Dc,0x66e46ab760374b08ddccab815720818dc9cd9883630b...,273,0x2655baab01d2b51e0d1adc7d5ac56b11e203ca59dbdd...,54,"{'reserve0': 13869825970761, 'reserve1': 35007..."

### (5) Extract Transfer Events

In [35]:
time.sleep(2)

In [36]:
rEvents = RetrieveEvents(connect, abi)
last_block = rEvents.latest_block()
start_block = last_block - 25000

In [37]:
events = rEvents.apply(EventType.TRANSFER, address = PAIR_ADDRESS_UNIV2, start_block=start_block, end_block=last_block)
rEvents.to_dataframe(events).head(2)

,blockNumber,event,address,blockHash,logIndex,transactionHash,transactionIndex,args
0,23442297,Transfer,0xB4e16d0168e52d35CaCD2c6185b44281Ec28C9Dc,0x7175112204acece784be97732ab1b95b46e9f8d44cf6...,989,0x8881c539057c4031f7e53549b8ea1ecb915eb2b2cbf0...,321,{'from': '0x1b56F238e1b9D32B802F9D05779f6C430B...
1,23442297,Transfer,0xB4e16d0168e52d35CaCD2c6185b44281Ec28C9Dc,0x7175112204acece784be97732ab1b95b46e9f8d44cf6...,990,0x8881c539057c4031f7e53549b8ea1ecb915eb2b2cbf0...,321,{'from': '0xB4e16d0168e52d35CaCD2c6185b44281Ec...